openapi: 3.0.0
info:
  version: '2018-04-01'
  x-release: v4
  title: 'Amazon Route 53 Resolver #X Amz Target=Route53Resolver.AssociateFirewallRuleGroup #X Amz Target=Route53Resolver.AssociateFirewallRuleGroup #X Amz Target=Route53Resolver.UpdateResolverEndpoint API'
  description: <p>When you create a VPC using Amazon VPC, you automatically get DNS resolution within the VPC from Route 53 Resolver. By default, Resolver answers DNS queries for VPC domain names such as domain names for EC2 instances or Elastic Load Balancing load balancers. Resolver performs recursive lookups against public name servers for all other domain names.</p> <p>You can also configure DNS resolution between your VPC and your network over a Direct Connect or VPN connection:</p> <p> <b>Forward DNS queries from resolvers on your network to Route 53 Resolver</b> </p> <p>DNS resolvers on your network can forward DNS queries to Resolver in a specified VPC. This allows your DNS resolvers to easily resolve domain names for Amazon Web Services resources such as EC2 instances or records in a Route 53 private hosted zone. For more information, see <a href="https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver.html#resolver-overview-forward-network-to-vpc">How DNS Resolvers on Your Network Forward DNS Queries to Route 53 Resolver</a> in the <i>Amazon Route 53 Developer Guide</i>.</p> <p> <b>Conditionally forward queries from a VPC to resolvers on your network</b> </p> <p>You can configure Resolver to forward queries that it receives from EC2 instances in your VPCs to DNS resolvers on your network. To forward selected queries, you create Resolver rules that specify the domain names for the DNS queries that you want to forward (such as example.com), and the IP addresses of the DNS resolvers on your network that you want to forward the queries to. If a query matches multiple rules (example.com, acme.example.com), Resolver chooses the rule with the most specific match (acme.example.com) and forwards the query to the IP addresses that you specified in that rule. For more information, see <a href="https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver.html#resolver-overview-forward-vpc-to-network">How Route 53 Resolver Forwards DNS Queries from Your VPCs to Your Network</a> in the <i>Amazon Route 53 Developer Guide</i>.</p> <p>Like Amazon VPC, Resolver is Regional. In each Region where you have VPCs, you can choose whether to forward queries from your VPCs to your network (outbound queries), from your network to your VPCs (inbound queries), or both.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: route53resolver
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/route53resolver-2018-04-01.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://route53resolver.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Route53Resolver multi-region endpoint
- url: https://route53resolver.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Route53Resolver multi-region endpoint
- url: http://route53resolver.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Route53Resolver endpoint for China (Beijing) and China (Ningxia)
- url: https://route53resolver.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Route53Resolver endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=Route53Resolver.UpdateResolverEndpoint'
paths:
  /#X-Amz-Target=Route53Resolver.UpdateResolverEndpoint:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: UpdateResolverEndpoint
      description: 'Updates the name, or enpoint type for an inbound or an outbound Resolver endpoint. You can only update between IPV4 and DUALSTACK, IPV6 endpoint type can''t be updated to other type. '
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateResolverEndpointResponse'
        '480':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '481':
          description: InvalidParameterException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParameterException'
        '482':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
        '483':
          description: InternalServiceErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceErrorException'
        '484':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateResolverEndpointRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - Route53Resolver.UpdateResolverEndpoint
      tags:
      - '#X Amz Target=Route53Resolver.UpdateResolverEndpoint'
components:
  schemas:
    ResourceNotFoundException: {}
    Ipv6:
      type: string
      minLength: 7
      maxLength: 39
    ResolverEndpoint:
      type: object
      properties:
        Id:
          allOf:
          - $ref: '#/components/schemas/ResourceId'
          - description: The ID of the Resolver endpoint.
        CreatorRequestId:
          allOf:
          - $ref: '#/components/schemas/CreatorRequestId'
          - description: A unique string that identifies the request that created the Resolver endpoint. The <code>CreatorRequestId</code> allows failed requests to be retried without the risk of running the operation twice.
        Arn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The ARN (Amazon Resource Name) for the Resolver endpoint.
        Name:
          allOf:
          - $ref: '#/components/schemas/Name'
          - description: The name that you assigned to the Resolver endpoint when you submitted a <a href="https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_CreateResolverEndpoint.html">CreateResolverEndpoint</a> request.
        SecurityGroupIds:
          allOf:
          - $ref: '#/components/schemas/SecurityGroupIds'
          - description: The ID of one or more security groups that control access to this VPC. The security group must include one or more inbound rules (for inbound endpoints) or outbound rules (for outbound endpoints). Inbound and outbound rules must allow TCP and UDP access. For inbound access, open port 53. For outbound access, open the port that you're using for DNS queries on your network.
        Direction:
          allOf:
          - $ref: '#/components/schemas/ResolverEndpointDirection'
          - description: '<p>Indicates whether the Resolver endpoint allows inbound or outbound DNS queries:</p> <ul> <li> <p> <code>INBOUND</code>: allows DNS queries to your VPC from your network</p> </li> <li> <p> <code>OUTBOUND</code>: allows DNS queries from your VPC to your network</p> </li> </ul>'
        IpAddressCount:
          allOf:
          - $ref: '#/components/schemas/IpAddressCount'
          - description: The number of IP addresses that the Resolver endpoint can use for DNS queries.
        HostVPCId:
          allOf:
          - $ref: '#/components/schemas/ResourceId'
          - description: The ID of the VPC that you want to create the Resolver endpoint in.
        Status:
          allOf:
          - $ref: '#/components/schemas/ResolverEndpointStatus'
          - description: '<p>A code that specifies the current status of the Resolver endpoint. Valid values include the following:</p> <ul> <li> <p> <code>CREATING</code>: Resolver is creating and configuring one or more Amazon VPC network interfaces for this endpoint.</p> </li> <li> <p> <code>OPERATIONAL</code>: The Amazon VPC network interfaces for this endpoint are correctly configured and able to pass inbound or outbound DNS queries between your network and Resolver.</p> </li> <li> <p> <code>UPDATING</code>: Resolver is associating or disassociating one or more network interfaces with this endpoint.</p> </li> <li> <p> <code>AUTO_RECOVERING</code>: Resolver is trying to recover one or more of the network interfaces that are associated with this endpoint. During the recovery process, the endpoint functions with limited capacity because of the limit on the number of DNS queries per IP address (per network interface). For the current limit, see <a href="https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html#limits-api-entities-resolver">Limits on Route 53 Resolver</a>.</p> </li> <li> <p> <code>ACTION_NEEDED</code>: This endpoint is unhealthy, and Resolver can''t automatically recover it. To resolve the problem, we recommend that you check each IP address that you associated with the endpoint. For each IP address that isn''t available, add another IP address and then delete the IP address that isn''t available. (An endpoint must always include at least two IP addresses.) A status of <code>ACTION_NEEDED</code> can have a variety of causes. Here are two common causes:</p> <ul> <li> <p>One or more of the network interfaces that are associated with the endpoint were deleted using Amazon VPC.</p> </li> <li> <p>The network interface couldn''t be created for some reason that''s outside the control of Resolver.</p> </li> </ul> </li> <li> <p> <code>DELETING</code>: Resolver is deleting this endpoint and the associated network interfaces.</p> </li> </ul>'
        StatusMessage:
          allOf:
          - $ref: '#/components/schemas/StatusMessage'
          - description: A detailed description of the status of the Resolver endpoint.
        CreationTime:
          allOf:
          - $ref: '#/components/schemas/Rfc3339TimeString'
          - description: The date and time that the endpoint was created, in Unix time format and Coordinated Universal Time (UTC).
        ModificationTime:
          allOf:
          - $ref: '#/components/schemas/Rfc3339TimeString'
          - description: The date and time that the endpoint was last modified, in Unix time format and Coordinated Universal Time (UTC).
        ResolverEndpointType:
          allOf:
          - $ref: '#/components/schemas/ResolverEndpointType'
          - description: ' The Resolver endpoint IP address type. '
      description: In the response to a <a href="https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_CreateResolverEndpoint.html">CreateResolverEndpoint</a>, <a href="https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_DeleteResolverEndpoint.html">DeleteResolverEndpoint</a>, <a href="https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_GetResolverEndpoint.html">GetResolverEndpoint</a>, Updates the name, or ResolverEndpointType for an endpoint, or <a href="https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_UpdateResolverEndpoint.html">UpdateResolverEndpoint</a> request, a complex type that contains settings for an existing inbound or outbound Resolver endpoint.
    ResolverEndpointType:
      type: string
      enum:
      - IPV6
      - IPV4
      - DUALSTACK
    Arn:
      type: string
      minLength: 1
      maxLength: 255
    ThrottlingException: {}
    InvalidParameterException: {}
    InvalidRequestException: {}
    ResourceId:
      type: string
      minLength: 1
      maxLength: 64
    ResolverEndpointStatus:
      type: string
      enum:
      - CREATING
      - OPERATIONAL
      - UPDATING
      - AUTO_RECOVERING
      - ACTION_NEEDED
      - DELETING
    InternalServiceErrorException: {}
    UpdateResolverEndpointRequest:
      type: object
      required:
      - ResolverEndpointId
      title: UpdateResolverEndpointRequest
      properties:
        ResolverEndpointId:
          allOf:
          - $ref: '#/components/schemas/ResourceId'
          - description: The ID of the Resolver endpoint that you want to update.
        Name:
          allOf:
          - $ref: '#/components/schemas/Name'
          - description: The name of the Resolver endpoint that you want to update.
        ResolverEndpointType:
          allOf:
          - $ref: '#/components/schemas/ResolverEndpointType'
          - description: ' Specifies the endpoint type for what type of IP address the endpoint uses to forward DNS queries. '
        UpdateIpAddresses:
          allOf:
          - $ref: '#/components/schemas/UpdateIpAddresses'
          - description: ' Updates the Resolver endpoint type to IpV4, Ipv6, or dual-stack. '
    StatusMessage:
      type: string
      maxLength: 255
    UpdateIpAddresses:
      type: array
      items:
        $ref: '#/components/schemas/UpdateIpAddress'
      minItems: 0
      maxItems: 50
    SecurityGroupIds:
      type: array
      items:
        $ref: '#/components/schemas/ResourceId'
    Name:
      type: string
      pattern: (?!^[0-9]+$)([a-zA-Z0-9\-_' ']+)
      maxLength: 64
    ResolverEndpointDirection:
      type: string
      enum:
      - INBOUND
      - OUTBOUND
    IpAddressCount:
      type: integer
    Rfc3339TimeString:
      type: string
      minLength: 20
      maxLength: 40
    UpdateIpAddress:
      type: object
      required:
      - IpId
      - Ipv6
      properties:
        IpId:
          allOf:
          - $ref: '#/components/schemas/ResourceId'
          - description: ' The ID of the IP address, specified by the <code>ResolverEndpointId</code>. '
        Ipv6:
          allOf:
          - $ref: '#/components/schemas/Ipv6'
          - description: ' The IPv6 address that you want to use for DNS queries. '
      description: ' Provides information about the IP address type in response to <a href="https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_UpdateResolverEndpoint.html">UpdateResolverEndpoint</a>. '
    CreatorRequestId:
      type: string
      minLength: 1
      maxLength: 255
    UpdateResolverEndpointResponse:
      type: object
      properties:
        ResolverEndpoint:
          allOf:
          - $ref: '#/components/schemas/ResolverEndpoint'
          - description: The response to an <code>UpdateResolverEndpoint</code> request.
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/route53resolver/
x-hasEquivalentPaths: true
